// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetCoreMVCSQL.Models;

#nullable disable

namespace NetCoreMVCSQL.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20211219050733_Inicial-criacao")]
    partial class Inicialcriacao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NetCoreMVCSQL.Models.Logistica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nome");

                    b.Property<string>("TipoCargueiro")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TipoCargueiro");

                    b.Property<string>("MinerioSaida")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MinerioSaida");

                    b.Property<DateTime>("DataSaida")
                        .HasColumnType("date")
                        .HasColumnName("DataSaida");

                    b.Property<DateTime>("DataRetorno")
                        .HasColumnType("date")
                        .HasColumnName("DataRetorno");

                    b.Property<string>("QtdObtida")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("QtdObtida");

                    b.Property<string>("MinerioObtido")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MinerioObtido");

                    b.Property<DateTime>("DataRecebido")
                        .HasColumnType("date")
                        .HasColumnName("DataRecebido");

                    b.Property<string>("ValorCarga")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ValorCarga");

                    b.HasKey("Id");

                    b.ToTable("Logistica");
                });
#pragma warning restore 612, 618
        }
    }
}
